language: ruby
rvm:
- 2.3.5
deploy:
  api_key:
    secure: LhH0eD5X68Pg9GsiZMp5Fx7XnozTrZ7TSB0oJi6zME72hkkmBA32mznSXl/sPp5CJS6kosTSjAQNzR1aUL1GKbSs/TjSWQH2ipgdL5fOfEXbNsfpYVM/fVfbFwdqFoZD7Ys09e0ROQCe7iO3bpN0UEJ5T/8Pz6mMhIGEqvLyHRpjUGGGuPDGvQsviQ10WCbkT04yi9tgK4N6dl4KwQlzp/2clEjg79qq/yH3EZiJmCSt+8d8PMuC6D4/XLU2wEgh3UZ+eWSz1jBPr0azM0tHXESE4j2KwgoHDCP8ydhiTqsYY0V3UJh0At80mY5qP73jvdl9nFGF8qLuDF1tYtdnX16pF7WDAwXpWd5ixuNq28+QT1pc5hsZbsYAO8mOulD79ej8I5VRV1DUOJ1lIyBD7Y91tC9ug5LaTIXHwCVgp866aYDhOrhfy/azWC5ul07qfXm1EJWKxLZGRtQkNlq5T7xiOouAoEc19y3hXkK1Hk+IjOaaQz3HEEnWAFmy+1Nd0zIyuTKfBtNh9WpAAHDr90o3KDrATIjunQB3+r5YCOhnR9itJxtGHnOlI09ovIr192lJbFbm9jm/uVvzGOua51jz10ZXo1s/Rm60zWoUyR9YIi55G0LEuL6GBekJPEOSeSEBp4G8lr5BDi6sEzXZnlMnD353eIZtpKZ+WuekMI8=
 provider: heroku
 app: rokhayasnk