env:
  global:
    - CC_TEST_REPORTER_ID=f9fecff72cf43ea395153a66dd4453ee14b7733fcf56705325396aedaa67bf3d
language: ruby
rvm:
- 2.3.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake 
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: sYFuqoGUMeDBpVDx+nllZXoE3GjBAyc2HGo2GOXXynSJgUjFnNtdlAup9wBa/szQQoRWInwPrLnQCMPObOvQFjxSUeqqHbLA4+XMDU3MBkUadyRvWuhweaalRtnESf1d20AMKcNCCE+s7aAM7bmgVUsQWOm1m79HaqxH63DNv9gtsMnAtSHmvLNA+frGyUI35mAAqaRNFOTYsWZFl+2E8YzK0/Re458PdWq4Nrg5G93lG6y//izfgG61pCOxNG375PUasA/VpkTg8WX5i6RB7l+LQOvCSuX74F4IvqRG0lBNjjDlUqtWWz4J2lcVGQzjqKKCFmhFXbMCQoBhXarupQOu0pKG+41y3vmkNPjG5FG5OFVteXvOjR3aGUB1nNvK/zLPb3ei94wT6vhDbBaIIeTCbV37row7Yx3TeUYs3dVZv1x62wp0YJUUwBEo4sBrGJkE4tLxOlk2xaZfsYRRVQn7aNmedUW436o8RhUCx0mFdJuHzbQOq3jbP3PMH+JWju95sDczu1GUnHrKVxXFAzCC8CGQcGQUHYTLWOoFOXBchJhb8hCyqaoTL7wDDsxpb2B687UaUbNHcDdkIr9h7M2Gb/BcG0QfCs8duGBajMMB7kxSbMRKK6/vXXPCZ2JItd+ZN67zLzECIx9dpD+uEStgAX7Vqo+sMK3SgmGfC08=
  app: rokhayasnk
  run: "rake db:migrate"
 